### ISSUE TITLE
syntax errors

### ISSUE THREAD

**Issue by madchap** [robbrucks/libzbxpgsql-streaming#1]
Hi,

Posting this issue early, just tried it out.

```
 2017-08-17 15:13:31.708 CEST >ERROR:  syntax error at or near "replpump" at character 1
< 2017-08-17 15:13:31.708 CEST >STATEMENT:  replpump
< 2017-08-17 15:13:31.715 CEST >ERROR:  syntax error at or near "dscrepslave" at character 1
< 2017-08-17 15:13:31.715 CEST >STATEMENT:  dscrepslave
< 2017-08-17 15:13:31.720 CEST >ERROR:  syntax error at or near "dscrepmstr" at character 1
< 2017-08-17 15:13:31.720 CEST >STATEMENT:  dscrepmstr
```

Running on PG 9.5.4 on CentOS7.

Thanks,
fred

**Comment by madchap** [comment]
Seeing this in the libzbxpqsql.conf file

```
you will also need to copy the streaming.conf file to /etc/zabbix
```

Yet, I would not know where to find this file?

**Comment by robbrucks** [comment]
Hi Fred,

What versions are you running for the following components:
- Zabbix server
- Zabbix agent
- libzbxpgsql

I want to be sure I set it up the same way to replicate the problem.

Also, you can ignore that comment about "streaming.conf".  It's remnants of an earlier monitoring attempt.

Thanks,
Rob

**Comment by madchap** [comment]
Hi,

* Zabbix 3.2.4 (soon to be upgraded to 3.2.7 just in case you want to wait)
* Zabbix agent 3.2.7
* libzbxpgsql 1.1.0

Thank you.
fred

**Comment by robbrucks** [comment]
I'm sorry @madchap, I've been swamped this week.  I'll get this set up and tested this weekend and try to figure out your issue.

My apologies and sorry for the delay.

**Comment by madchap** [comment]
No need to apologize @robbrucks ! Thanks for the awesome extension rather! Let me know if I can provide you with additional details.

**Comment by robbrucks** [comment]
Hey @madchap,

I'm not able to reproduce the issue, but I do have a couple of ideas.

What point version of Centos 7 are you running?
Is the libconfig package installed, and what version is it?
Did you modify the `libconfig.conf` file?  If so, can you share it with me?

Those syntax errors are likely coming from libconfig as it parses the `libzbxpgsql.conf` config file, so I suspect an issue there.  Either a syntax error in the config file or an older version of libconfig that can't properly parse it.

Thanks,
Rob

**Comment by robbrucks** [comment]
Hey @madchap,

I figured it out.  You skipped step 2, you need to copy the `libzbxpgsql.conf` file from this repo to your DB servers into the /etc/zabbix directory.  Make sure it has the proper permissions to allow the zabbix agent to read it too.

That should fix your problem.

--Rob

**Comment by madchap** [comment]
Hey Rob,

Unfortunately, the file is on both my DB servers.

centos version:
centos-release-7-3.1611.el7.centos.x86_64

libconfig version: 
libconfig-1.4.9-5.el7.x86_64

I don't seem to have a libconfig.conf file anywhere on the system.

**Comment by madchap** [comment]
Btw, zabbix server was updated to 3.2.7 too. That didn't change anything (as expected).

**Comment by madchap** [comment]
Also, it actually works for the lag. It is just these 3 commands that error out.

![image](https://user-images.githubusercontent.com/5468769/29753833-0653b516-8b7a-11e7-8839-5e40a7f566b4.png)

**Comment by madchap** [comment]
Damn me. I had forgotten something indeed. the GRANT on the function to my zabbix user :-/ 
However, it seems I am not getting any data (but it's not greyed out anymore), I get regular errors as such as:

```
< 2017-08-27 23:07:10.746 CEST >ERROR:  permission denied for tablespace pg_global
< 2017-08-27 23:07:10.746 CEST >STATEMENT:  SELECT pg_tablespace_size($1)
```

Would that be related? (I think it comes from the regular libzbxpgsql monitoring). I am guessing the user would need superuser role.

**Comment by robbrucks** [comment]
Did you get the syntax errors resolved?  If not, copy my libzbxpgsql.conf file from this repo to /etc/zabbix directory on your DB servers and then restart the zabbix agent. That should get rid of the errors.

The permission errors about the tablespaces are coming from the libzbxpgsql plugin that Ryan developed, they're not from this plugin. I get those errors too on my servers. Those require your user to be a superuser to function properly.

To stop the tablespace errors you can either grant superuser to your zabbix DB user or disable the "PostgreSQL Tablespace disk size on..." items for the hosts.

Let me know if you still have any issues.

--Rob

**Comment by madchap** [comment]
Yes, no more error in the logs. However, I do not get any values back at all (the item is not greyed out anymore) and has become supported in zabbix.

![image](https://user-images.githubusercontent.com/5468769/29761059-8e82682c-8bc7-11e7-9811-b219a3cce95b.png)

**Comment by robbrucks** [comment]
Which metrics are missing values?

**Comment by madchap** [comment]
Streaming Replication Log Pump, the one that was greyed out in the above screenshot. Now it is "ok", but no data as shown above. Not sure what kind of data is to be seen here.

**Comment by robbrucks** [comment]
That one doesn't gather any metrics.  It's a fake metric that just calls the function included with this monitoring every 30 seconds.  Take a look at the README for this repo and it has a lengthy explanation of why I use it.

But no, that metric isn't supposed to return any data.

--Rob

**Comment by madchap** [comment]
OK thanks. So this is closed then, the real issue was the fact that I had not applied the EXECUTE FUNCTION grant to the zabbix role.

Thanks for your kind help and for the plugin.

Cheers,
fred

**Comment by robbrucks** [comment]
Glad you find it useful @madchap!
