### ISSUE TITLE
Unsupported version number

### ISSUE THREAD

**Issue by hnguyen412** [robbrucks/libzbxpgsql-streaming#2]
- Zabbix Server:  3.0.12
- libzbxpgsql-1.1.0 installed with zabbix agent in my DB server
I got the error when i import the xml file (postgresql_streaming_template.xml):

>     Invalid tag "/zabbix_export/version": unsupported version number.

**Comment by robbrucks** [comment]
I originally created this on Zabbix 3.4, so it will complain when imported into an earlier Zabbix version.

I updated the template to Zabbix version 3.0 format so you should be able to import it into your Zabbix system now.
